// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview This file defines a Genkit flow for analyzing sales trends from transaction data.
 *
 * - analyzeSalesTrends - A function that triggers the sales trend analysis flow.
 * - SalesAnalysisInput - The input type for the analyzeSalesTrends function.
 * - SalesAnalysis - The output type for the analyzeSalesTrends function (renamed from Output for clarity).
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';
import type { TransactionDetail } from '@/lib/data';

const SalesAnalysisInputSchema = z.object({
  transactions: z.array(z.any()).describe("An array of transaction objects to be analyzed."),
});
export type SalesAnalysisInput = z.infer<typeof SalesAnalysisInputSchema>;

const SalesAnalysisSchema = z.object({
  trendAnalysis: z.string().describe("A summary of sales trends, like performance of certain product categories or overall sales velocity."),
  salesPrediction: z.string().describe("A prediction for future sales based on the provided historical data."),
  peakSalesTime: z.string().describe("The time of day or week when sales are highest."),
  topPerformingCategories: z.array(z.string()).describe("A list of the best-performing product categories."),
});
export type SalesAnalysis = z.infer<typeof SalesAnalysisSchema>;

export async function analyzeSalesTrends(input: { transactions: TransactionDetail[] }): Promise<SalesAnalysis> {
    // We pass the raw transaction detail to the flow, as z.any() will accept it.
    // The prompt is engineered to handle the detailed structure.
    return analyzeSalesTrendsFlow(input);
}


const analyzeSalesTrendsPrompt = ai.definePrompt({
  name: 'analyzeSalesTrendsPrompt',
  input: { schema: SalesAnalysisInputSchema },
  output: { schema: SalesAnalysisSchema },
  prompt: `You are a professional business analyst AI. Your task is to analyze the provided transaction data and generate a concise report covering sales trends, predictions, and key insights.

Analyze the following JSON transaction data:
{{{json transactions}}}

Based on your analysis, provide the following insights:
- trendAnalysis: Briefly describe the overall sales trend. Are sales increasing, decreasing, or stable? Are there any notable patterns in product categories?
- salesPrediction: Based on the trend, provide a short-term sales prediction. For example, "Sales are expected to increase by 10-15% next month."
- peakSalesTime: Identify the days of the week or times of day when sales are most frequent.
- topPerformingCategories: List the top 3-5 product categories based on sales volume and revenue.

Your response must be in JSON format.`,
});

const analyzeSalesTrendsFlow = ai.defineFlow(
  {
    name: 'analyzeSalesTrendsFlow',
    inputSchema: SalesAnalysisInputSchema,
    outputSchema: SalesAnalysisSchema,
  },
  async (input) => {
    const { output } = await analyzeSalesTrendsPrompt(input);
    return output!;
  }
);
