// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that suggests product descriptions based on product name and keywords.
 *
 * - suggestProductDescription - A function that handles the product description suggestion process.
 * - SuggestProductDescriptionInput - The input type for the suggestProductDescription function.
 * - SuggestProductDescriptionOutput - The return type for the suggestProductDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestProductDescriptionInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  keywords: z.string().describe('A few keywords related to the product.'),
});
export type SuggestProductDescriptionInput = z.infer<typeof SuggestProductDescriptionInputSchema>;

const SuggestProductDescriptionOutputSchema = z.object({
  description: z.string().describe('The suggested product description.'),
});
export type SuggestProductDescriptionOutput = z.infer<typeof SuggestProductDescriptionOutputSchema>;

export async function suggestProductDescription(input: SuggestProductDescriptionInput): Promise<SuggestProductDescriptionOutput> {
  return suggestProductDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestProductDescriptionPrompt',
  input: {schema: SuggestProductDescriptionInputSchema},
  output: {schema: SuggestProductDescriptionOutputSchema},
  prompt: `You are an expert copywriter. Your task is to generate a compelling product description.

  Based on the product name and keywords provided, create a product description that is engaging and informative.

  Product Name: {{{productName}}}
  Keywords: {{{keywords}}}

  Generate a product description.
  Output should follow this format:
  {
    "description": "The suggested product description."
  }`,
});

const suggestProductDescriptionFlow = ai.defineFlow(
  {
    name: 'suggestProductDescriptionFlow',
    inputSchema: SuggestProductDescriptionInputSchema,
    outputSchema: SuggestProductDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
