// This is an autogenerated file from Firebase Studio.

import { initializeApp, getApps, getApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {
  "projectId": "shopassist-pos",
  "appId": "1:139902766975:web:22d494c9b77b632437144a",
  "storageBucket": "shopassist-pos.firebasestorage.app",
  "apiKey": "AIzaSyBAvTTRTiK4SWRRn7TtyyYPNFuQrnU-xqc",
  "authDomain": "shopassist-pos.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "139902766975"
};

// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
const db = getFirestore(app);

export { app, db };
